### ISSUE TITLE
Missing `RefreshConfig` method

### ISSUE THREAD

**Issue by panz3r** [nearit/Cordova-SDK#1]
`RefreshConfig` method should be available to the JavaScript side

See NearIT docs:
- `refreshConfigWithCompletionHandler` on iOS: http://nearit-ios.readthedocs.io/en/latest/installation/
- `refreshConfigs(recipeRefreshListener)` on Android: http://nearit-android.readthedocs.io/en/latest/installation/

**Comment by lidio601** [comment]
Hi @panz3r, please test and close.
cheers

**Comment by panz3r** [comment]
Hi @lidio601 , 

I tried with the `Sample` app and in the `Logs` section I only see the call to the method
`demo :: calling nearit.refreshRecipes( - - )`
but no callback seems to be fired
(I expect to see something like `demo :: refreshRecipes successCb`)

**Comment by panz3r** [comment]
Running from XCode, I get this WARN
```NearITDemo[744:108128] WARN: Unhandled rejection file:///var/containers/Bundle/Application/FA3B7E90-113C-4AE8-81E1-51269034D553/NearITDemo.app/www/js/controllers.js:67:34```

**Comment by panz3r** [comment]
Removing and Adding the plugin again fixed the issue.
