### ISSUE TITLE
`setUserData` does not work for `Sample` app

### ISSUE THREAD

**Issue by panz3r** [nearit/Cordova-SDK#3]
Trying to set user data from `User Data` section of `Sample` app seems to not work (On NearIT CMS user data are not displayed correctly)

**Comment by lidio601** [comment]
Javascript part seems working fine here:

<img width="294" alt="schermata 2017-08-01 alle 18 10 13" src="https://user-images.githubusercontent.com/579163/28835142-b33984b8-76e4-11e7-96d7-dcbd4af72a4d.png">

Also I receive this log within Xcode debug:

<img width="908" alt="schermata 2017-08-01 alle 18 11 45" src="https://user-images.githubusercontent.com/579163/28835212-e83982c6-76e4-11e7-9849-77d17e9f06c3.png">

Which is my log [here](https://github.com/nearit/Cordova-SDK/blob/master/src/ios/CDVNearIT.m#L255)

I wonder if:

- @panz3r did you change  _<preference name="nearit-api-key" value="Your.Api.Key" />_  preference within _sample/config.xml_ ?
- @TheFlynn it seems to me that I'm reaching SDK [here](https://github.com/nearit/Cordova-SDK/blob/master/src/ios/CDVNearIT.m#L255), any advice?

**Comment by panz3r** [comment]
@lidio601 Yes, I changed `nearit-api-key` inside `sample/config.xml` to match the one for my App on `go.nearit.com`

**Comment by TheFlynn** [comment]
@lidio601 setDeferredUserDataWithKey issue is resolved from version 1.0.8

**Comment by lidio601** [comment]
Ok, I'm gonna update cordova-sdk to use [Near-iOs-SDK v.1.0.8](https://github.com/nearit/Near-iOS-SDK/releases/tag/1.0.8) then

**Comment by lidio601** [comment]
Hi @panz3r,
please test and close this issue if passed.

**Comment by panz3r** [comment]
Hi @lidio601 ,
Tested on iOS and is working as expected (both the `Gender` data-point and another custom one)
